blank_issues_enabled: false
contact_links:
  - name: Reportar un bug
    url: https://github.com/agh45-ua/MasterPiece/issues/new?template=bug_report.md
    about: Usa esta plantilla para informar de un error
